### PR TITLE
Adds i18n settings and Chinese docs

### PR DESCRIPTION
**Pull request by vickyhella**
This PR also upgrades Docusaurus to 2.1.0, as it has better support for multi-language settings

### CODE REVIEW

**Comment by gunamata** [comment]
@vickyhella - Thank you for the PR. I noticed the DCO check has failed, Can you please sign your commit? It's simple, please follow instructions on the page - https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/102/checks?check_run_id=8426636476

**Comment by vickyhella** [comment]
@gunamata I have signed my commit, but DCO check is still failing and CI is not running. Not sure if DCO can only work after CI is run.
cc @btat 
image

**Comment by jandubois** [comment]
> I have signed my commit, but DCO check is still failing

You must sign every commit in the PR, not just the last one. The first commit (Docusaurus update) is still missing DCO:

```
commit bd9787d7aacf0fa5a5a6553c8aa9f24b60d78c4d (HEAD -> vk-translation)
Author: vickyhella <vickyhella@hotmail.com>
Date:   Tue Sep 20 10:19:21 2022 +0800

    Add i18n and Chinese docs

    Signed-off-by: vickyhella <vickyhella@hotmail.com>

commit ad22ccdd4e6c97225db4f061900996833618e8a6
Author: vickyhella <vickyhella@hotmail.com>
Date:   Mon Sep 19 18:12:34 2022 +0800

    Upgrade Docusaurus to 2.1.0
```

**Comment by jandubois** [comment]
> CI is not running

That's because it is your first PR to this repo; I've approved running the CI now; future PRs from you should run CI automatically (but will still require DCO on every commit).

**Comment by vickyhella** [comment]
DCO check is resolved. Please approve the CI again. Thanks @jandubois

**Comment by gunamata** [comment]
@vickyhella , Is there any special setup that I need to do to see the localization changes on my machine. I ran below commands on your PR branch, and when I switch to `Chinese` language, I see `Page not found`..

```
yarn
yarn run build
yarn start
```

image

**Comment by vickyhella** [comment]
@gunamata, Please run `yarn build` and then `yarn serve`.

**Review by gunamata — APPROVED** [review]
LGTM

**Pull request merged**
