### PR TITLE
Update Chinese translation for all versions

### PR DESCRIPTION
**Pull request by vickyhella**
Signed-off-by: vickyhella <vickyhella@hotmail.com>

### CODE REVIEW

**Comment by gunamata** [comment]
Some observations:

- Chinese docs do not seem to show the newly added application screenshot images. For example, on the `User Interface > General` page, english version shows an image whereas the chinese doesn't. As part of the `1.7.0` we added screenshots to most of the `User Interface > Preferences` pages and a few other pages.
- The content for the page `User Interface > Preferences > Container Engine` is not in sync between the Chinese and the English versions

@vickyhella , Can you please take care of the above observations?

**Comment by vickyhella** [comment]
> Some observations:
> 
> * Chinese docs do not seem to show the newly added application screenshot images. For example, on the `User Interface > General` page, english version shows an image whereas the chinese doesn't. As part of the `1.7.0` we added screenshots to most of the `User Interface > Preferences` pages and a few other pages.
> * The content for the page `User Interface > Preferences > Container Engine` is not in sync between the Chinese and the English versions
> 
> @vickyhella , Can you please take care of the above observations?

- @gunamata  I think the screenshots were already added as shown below (for all versions). Would you please double-check if you are looking at the right place/branch? Or it'd be great if you can help provide an image to show which screenshots are missing. ^^
	`User Interface > General` page:
	image
	`User Interface > Preferences > Application` page:
	image

- I think the content is already in sync with the latest main branch. Again, please double-check or provide an image~~
	image

**Comment by gunamata** [comment]
Hi @vickyhella, I have just realized I missed to run `npm build`. Apologies for the confusion. The images appear on pages as expected.

However, The Chinese version shows `Page Not Found` when I follow below steps on the local version. The same steps work fine on the LIVE version though. Here are the steps:

- `npm run build`
- `npm run serve`
- Go to `localhost:3000`. By default, the english version is loaded with `Latest` as the selected version.
- Select the version  `1.7` from the drop down.
- Switch to the Chinese version. At this point, I see `Page Not Found`.

image

**Comment by gunamata** [comment]
Update to my last comment above: I noticed `Page Not Found` error while working on the PR https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/139 as well. It looks like this is a problem only in the dev environment. 

@nunix - I remember you mentioning some known limitation about the Chinese version. Is this the error you were referring to ? If yes, I am okay to marge this PR as the problem is only in the local development environment.

**Comment by vickyhella** [comment]
> Update to my last comment above: I noticed `Page Not Found` error while working on the PR #139 as well. It looks like this is a problem only in the dev environment.
> 
> @nunix - I remember you mentioning some known limitation about the Chinese version. Is this the error you were referring to ? If yes, I am okay to marge this PR as the problem is only in the local development environment.

@gunamata I noticed this error too. It happens when you switch versions and locales in the sequence you mentioned (I kinda remember switching the locale first and then the version does not have this problem). But according to my previous observations, it only occurs in dev and should be fine in production (hopefully).

**Comment by gunamata** [comment]
Merging this as the observation in the comment above only seems to happen in the development environment.

**Review by gunamata — APPROVED** [review]

**Pull request merged**
