### PR TITLE
Adding missing instruction for running skaffold

### PR DESCRIPTION
**Pull request by inglkruiz**
While running the how to guide I realised that a simple missing instruction could improve it.

### CODE REVIEW

**Comment by gunamata** [comment]
@inglkruiz , Thank you for the PR. Can you please sign the commit. You can follow instructions on [this page](https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/105/checks?check_run_id=8549585063) to sign your commit,

**Comment by inglkruiz** [comment]
> @inglkruiz , Thank you for the PR. Can you please sign the commit. You can follow instructions on [this page](https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/105/checks?check_run_id=8549585063) to sign your commit,

@gunamata Done

**Comment by gunamata** [comment]
@inglkruiz , I still see that the DCO check has failed. Did you sign your commit?

**Comment by inglkruiz** [comment]
> @inglkruiz , I still see that the DCO check has failed. Did you sign your commit?

Silly me, I did  `git commit -S` understanding that I had to use my GPG-sign only, I did not add `--signoff`. My apologies.

**Review by gunamata — APPROVED** [review]
LGTM

**Pull request merged**
