### PR TITLE
Add step 5 - apply CRDs  to make this recipe work

### PR DESCRIPTION
**Pull request by kevinayres**
Signed-off-by: Kevin Ayres kevin.ayres@suse.com

### CODE REVIEW

**Comment by sunilarjun** [comment]
Hello there, could you please add a DCO to your commit?
https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/204/checks?check_run_id=12933093900
Thanks!

**Comment by adamkpickering** [comment]
Going through the steps, I get the following on the step you added:
```
docs.rancherdesktop.io\> kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
Warning: resource customresourcedefinitions/certificaterequests.cert-manager.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io configured
Warning: resource customresourcedefinitions/certificates.cert-manager.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io configured
Warning: resource customresourcedefinitions/challenges.acme.cert-manager.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io configured
Warning: resource customresourcedefinitions/clusterissuers.cert-manager.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io configured
Warning: resource customresourcedefinitions/issuers.cert-manager.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io configured
Warning: resource customresourcedefinitions/orders.acme.cert-manager.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io configured
```
Is this expected?

On the final step, I get the following error:
```
docs.rancherdesktop.io\> helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher.rd.localhost --wait --timeout=10m
Error: INSTALLATION FAILED: execution error at (rancher/templates/validate-psp-install.yaml:4:5): The target cluster does not have the PodSecurityPolicy API resource. Please disable PSPs in this chart before proceeding.
```
@sunilarjun I'll let you take it from here - I'd imagine you know the context for these docs better than me.

**Comment by kevinayres** [comment]
@sunilarjun @adamkpickering  I got different results. My only goal is to make sure the published recipe works and if it's proofed w/o my PR then I can delete it.

**Comment by sunilarjun** [comment]
@kevinayres Hello! I tested your additional step locally and had success. Applying the CRD's is a necessary step as without it I was running into this error when following the helm steps:

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "rancher" namespace: "" from "": no matches for kind "Issuer" in version "cert-manager.io/v1"
ensure CRDs are installed first
```

In order for us to accept this PR could you please fix the [DCO issue](https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/204/checks?check_run_id=12933093900) as we are unable to merge with it failing. Thank you for your work!

**Comment by kevinayres** [comment]
I edited the following to my original comment for the PR "Signed-off-by: Kevin Ayres kevin.ayres@suse.com"

Am I missing something? Thanks

**Comment by sunilarjun** [comment]
I don't believe editing the comment with approval will work against the automated testing, I think following these steps under `Rebase the branch` should [sign all your necessary commits](https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/204/checks?check_run_id=12933093900#:~:text=can%20be%20merged.-,Rebase%20the%20branch,-If%20you%20have). Let me know if this helps, thanks!

**Comment by sunilarjun** [comment]
Hello! I made a PR linked above that includes these changes so going to close this one out. Thank you for the work on the update!

**Comment by kevinayres** [comment]
Sorry guys – going in 5 directions today. I had on my list to rebase this today, but I appreciate you!

Kevin

From: Sunil Singh ***@***.***>
Date: Wednesday, April 26, 2023 at 1:44 PM
To: rancher-sandbox/docs.rancherdesktop.io ***@***.***>
Cc: Kevin Ayres ***@***.***>, Mention ***@***.***>
Subject: Re: [rancher-sandbox/docs.rancherdesktop.io] Add step 5 - apply CRDs to make this recipe work (PR #204)

Hello! I made a PR linked above that includes these changes so going to close this one out. Thank you for the work on the update!

**Pull request closed without merging**
