### PR TITLE
1.12 Docs Release

### PR DESCRIPTION
**Pull request by sunilarjun**
This PR and initial commit includes changes for the Rancher Desktop 1.12 documentation release, and updates the bundled utilities for 1.12 in the references section.

Only merge once the 1.12 Rancher Desktop release is out.

### CODE REVIEW

**Comment by gunamata** [comment]
@sunilarjun , The Linux screenshots are available in the `Rancher Desktop` shared folder on the Google Drive

**Comment by sunilarjun** [comment]
Added Linux screenshot updates to versions Next, Latest, and 1.12 for the UI/Preferences sections.

**Comment by gaktive** [comment]
Late breaking bonus win that with https://github.com/rancher-sandbox/rancher-desktop/pull/6264, we have native M1 support in this release. I couldn't find references to Rosetta explicitly in our docs but we can add something to the release notes at least.

**Comment by sunilarjun** [comment]
All screenshots have been updated for Linux, macOS, and Windows platforms across the latest 1.12 versions.

**Review by gunamata — APPROVED** [review]
LGTM

**Pull request merged**
