### PR TITLE
Fix command for workaround for disabling Kubernetes

### PR DESCRIPTION
**Pull request by adamfeldman**
➜  ~ kubectl config use-context rancher-desktop
Switched to context "rancher-desktop".
➜  ~ kubectl delete node lima rancher-desktop
Error from server (NotFound): nodes "lima" not found
Error from server (NotFound): nodes "rancher-desktop" not found
➜  ~ kubectl delete node lima-rancher-desktop
node "lima-rancher-desktop" deleted

### CODE REVIEW

**Comment by jandubois** [comment]
This PR is missing a DCO signature.

But more importantly, do the commands actually work? In my testing all the containers continued to run after I deleted the node (which is kind of what I was expecting), so how does this help to "stop kubernetes"?

**Comment by adamfeldman** [comment]
@jandubois the commit was amended with a DCO signature, is the signature required elsewhere too?

In this PR, I am only fixing the documented command so it runs without error and matches the [related issue comment](https://github.com/rancher-sandbox/rancher-desktop/issues/985#issuecomment-1015592658). 

I found that the command worked on both my Intel and M1 macOS laptops, with some usability caveats:
* After opening Rancher Desktop and waiting for the UI to say it's done starting, running  showed the pods running.

I'm running Rancher Desktop 1.0.0.

I am only a user of this project and casually experimenting to see if Rancher Desktop will meet my needs (which don't require k8s right now).

**Comment by adamfeldman** [comment]
@jandubois the commit was amended with a DCO signature, is the DCO signature required elsewhere too?

In this PR, I am only fixing the _workaround_ command from this FAQ so it runs without error and matches the [related issue comment](https://github.com/rancher-sandbox/rancher-desktop/issues/985#issuecomment-1015592658). 

I am only a user of this project and casually experimenting to see if Rancher Desktop will meet my needs (which don't require k8s right now).

I found that the command worked on both Intel and M1 macOS laptops, with some usability caveats. I'm running Rancher Desktop 1.0.0:

* After first installing and opening Rancher Desktop, and waiting for the UI to say it's done starting, running `kubectl get pods -A` showed the pods running.
<details>
  <summary>Click to expand</summary>

```
➜  ~ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   coredns-5789895cd-bdc5c                   1/1     Running   0          14m
kube-system   svclb-traefik-jdk29                       2/2     Running   0          5m42s
kube-system   local-path-provisioner-6c79684f77-lm2dq   1/1     Running   0          14m
kube-system   metrics-server-7cd5fcb6b7-6pr4d           1/1     Running   0          14m
kube-system   traefik-6bb96f9bd8-5jx9n                  1/1     Running   0          14m
```
</details>

* After running `kubectl delete node lima rancher-desktop`, the pods go to pending after 5-15 minutes (I didn't pay close attention to the delay time).
<details>
  <summary>Click to expand</summary>

```
➜  ~ kubectl get pods -A                     
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   traefik-6bb96f9bd8-hqb6v                  0/1     Pending   0          12m
kube-system   metrics-server-7cd5fcb6b7-f9hnv           0/1     Pending   0          12m
kube-system   local-path-provisioner-6c79684f77-2dxm7   0/1     Pending   0          12m
kube-system   coredns-5789895cd-wpjzx                   0/1     Pending   0          12m
```
</details>

* After quitting and reopening Rancher Desktop, the k8s pods still go into the `Running` status, but get to `Pending` eventually

**Comment by jandubois** [comment]
> I am only a user of this project and casually experimenting to see if Rancher Desktop will meet my needs (which don't require k8s right now).

I know. I'm sorry, most of my comments were directed at the docs persons: why do we document a workaround, that didn't seem  to work in my testing. I didn't expect you to respond to this!

>  * After running `kubectl delete node lima rancher-desktop`, the pods go to pending after 5-15 minutes (I didn't pay close attention to the delay time).

That is interesting. Maybe I didn't wait long enough; will have to try this again.

> * After quitting and reopening Rancher Desktop, the k8s pods still go into the `Running` status, but get to `Pending` eventually

This one is really surprising to me: when you restart k3s, it should re-create the node, so it should no longer be "paused".

Thank you for your detailed response; I will definitely need to look into this some more!

**Comment by adamfeldman** [comment]
Thanks @jandubois, all good, I needed to do and document this testing anyways! 😁 

> > * After quitting and reopening Rancher Desktop, the k8s pods still go into the `Running` status, but get to `Pending` eventually
> 
> This one is really surprising to me: when you restart k3s, it should re-create the node, so it should no longer be "paused"

Yes, that's exactly what I observed – 
1. I restarted k3s by quitting Rancher Desktop
2. As soon as Rancher Desktop UI showed it was done booting per the macOS UI, I ran `kubectl get pods -A` a few times and observed the pods start and get to `Running`
3. _Eventually_ the pods landed on `Pending` as desired.

FWIW, I'm here looking for a new way to run a Docker-API-compatible container daemon on our work macOS dev machines. We currently run dev boxes and also prod via `docker-compose` – I'm hoping Rancher Desktop will meet our needs till we inevitably move everything to k8s X years down the line 😃

**Comment by jeesmon** [comment]
Followed the steps and it worked great. For me it took a minute or two get `kubectl get po -A` to show all pods in `Pending` status. I also ran `docker system prune` to remove exited containers from `docker ps -a` list.

**Review by gunamata — APPROVED** [review]
Thank you for catching this.

**Pull request merged**
